name: Time Support Action
description: Block your workflow if is out of maintenance time
author: Jonathan Delgado <hi@jon.soy> (https://jon.soy)
inputs:
  option:
    description: Configuration of maintenance time
    default: |
      maintenance:
        - since: "19:00"
          until: "22:00"
          timeZone: America/Santiago
    required: true
outputs:
  available:
    description: Result of evaluation
runs:
  using: node16
  main: action.js
