on: push

permissions:
  contents: write
  pull-requests: write

name: Release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # - uses: google-github-actions/release-please-action@v3
      #   with:
      #     release-type: node
      #     package-name: time-support-action
      #     token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm test
      - run: git switch -c release/new-version
      - run: git push --set-upstream origin release/new-version

